version: "3"
services:
  php:
    build: ./docker-php
    working_dir: /var/www
    volumes:
      - ./:/var/www

  nginx:
    build: ./docker-nginx
    working_dir: /var/www
    volumes_from:
      - php
    ports:
      - 80:80