version: "3"
services:
  php:
    build: ./docker-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  nginx:
    build: ./docker-nginx
    working_dir: /var/www
    volumes_from:
      - php
    ports:
      - 80:80
    networks:
      - app-network

  database:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql1:/usr/share/elasticsearch/data
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - 6379:6379
    networks:
      - app-network

  elasticsearch:
    image: elasticsearch:7.9.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  esdata1:
    driver: local
  mysql1:
    driver: local

